version: "3" 
services:

  reactapp:
    build: ./frontend
    container_name: "api_client"
    depends_on:
      - server
    ports:
      - 5000:3000
    environment:
      - REACT_APP_URI=http://localhost:4000

  server:
    build: ./backend
    container_name: "api_server"   
    ports:
      - 4000:3000
    depends_on:
      - database
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr

  database:
    image: khaashifriaz/gigstr:gigtag   
    container_name: "gigstr-db-container"
    environment:
      - POSTGRES_PASSWORD=gigstr
    ports:
      - 5432:5432

   

# docker run --name my-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres