version: "3" 
services:

  reactapp:
    build: ./frontend
    container_name: "api_client"
    depends_on:
      - server
    ports:
      - 5000:3000

  server:
    build: ./backend
    container_name: "api_server"   
    ports:
      - 4000:3000



    # environment:
    #   - DB_HOSTNAME=my-postgres
    #   - DB_PASSWORD=mysecretpassword
  # database:
  #   image: postgres:latest
  #   container_name: my-postgres
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #   ports:
  #     - 5432:5432

# docker run --name my-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres