name: Docker React CI Frontend

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      working-directory: frontend

    - name: Build the Docker image
      run: docker build -t khaashifriaz/react3:v1 .
      working-directory: frontend

    - name: Push the docker image
      run: docker push khaashifriaz/react3:v1
      working-directory: frontend
    