name: Docker React CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      working-directory: bigdatabase
      
    - name: Build the Docker image
      run: docker build -t khaashifriaz/gigstr:team3 .
      working-directory: bigdatabase

    - name: Push the docker image
      run: docker push khaashifriaz/gigstr:team3
      working-directory: bigdatabase