name: Docker React CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      working-dir: frontend

    - name: Build the Docker image
      run: docker build -t khaashifriaz/gigstr:react3 .
      working-dir: frontend

    - name: Push the docker image
      run: docker push khaashifriaz/gigstr:react3
      working-dir: frontend
      
    #i hope this works lol
    #this yml file should be for database right, otherwise its just a duplicate of the frontend?